### ISSUE TITLE
Convert the RDS instance resource from patch-and-transform to go-templating function

### ISSUE THREAD

**Issue by Smana** [Smana/demo-secured-eks#16]
This will allow to add a condition on the DB port.

**Comment by Smana** [comment]
I used a map instead
```yaml
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.engine
                toFieldPath: spec.forProvider.manifest.spec.ports[0].port
                transforms:
                  - map:
                      postgres: 5432
                      mariadb: 3306
                    type: map
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.engine
                toFieldPath: spec.forProvider.manifest.spec.ports[0].targetPort
                transforms:
                  - map:
                      postgres: 5432
                      mariadb: 3306
                    type: map
```
